import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Pi7 exact brand colors
        background: "#ffffff",
        foreground: "#2b2f52",
        "pcolor": "#4449A6",
        "scolor": "#d31b5a",
        "btn-teal": "#047e73",
        "btn-teal-hover": "#036960",
        primary: "#4449A6",
        "on-primary": "#ffffff",
        secondary: "#d31b5a",
        "on-secondary": "#ffffff",
        "accent-lavender": "#4449A6",
        "accent-yellow": "#ffeb3b",
        "border-dashed": "#9da0d9",
        border: "#d9dcea",
        outline: "#8b90ab",
        "outline-variant": "#e3e4ef",
        "text-secondary": "#6e7288",
        muted: "#eff0fa",
        surface: "#ffffff",
        "surface-container": "#f7f8fc",
        "surface-container-high": "#eff0fa",
        "surface-container-low": "#fafbfe",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#f0f2f9",
        "surface-bright": "#ffffff",
        error: "#d31b5a",
        "on-error": "#ffffff",
        "error-container": "#ffebee",
        "on-error-container": "#c62828",
      },
      borderRadius: {
        DEFAULT: "3px",
        sm: "2px",
        md: "4px",
        lg: "6px",
        xl: "8px",
        "2xl": "12px",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-geist-sans)", "sans-serif"],
        "headline-xl": ["var(--font-geist-sans)", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "sans-serif"],
        "headline-sm": ["var(--font-geist-sans)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-geist-sans)", "sans-serif"],
        "body-lg": ["var(--font-geist-sans)", "sans-serif"],
        "body-md": ["var(--font-geist-sans)", "sans-serif"],
        "body-sm": ["var(--font-geist-sans)", "sans-serif"],
        sans: ["var(--font-geist-sans)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-xl": ["60px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        "soft-md": "0 4px 20px rgba(0,0,0,0.3)",
      },
    },
  },
  plugins: [],
};
export default config;
