import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material-style surface system used by every Stitch export
        background: "#131315",
        foreground: "#e5e1e4",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1b1b1b",
        tertiary: "#ffffff",
        "on-surface": "#e5e1e4",
        "surface-container-low": "#1c1b1d",
        "surface-container-lowest": "#0e0e10",
        "on-primary-container": "#636565",
        "surface-container": "#201f22",
        "inverse-on-surface": "#313032",
        "primary-fixed": "#e2e2e2",
        "on-error": "#690005",
        "on-primary-fixed": "#1a1c1c",
        muted: "#18181B",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed-variant": "#474747",
        "inverse-surface": "#e5e1e4",
        border: "#27272A",
        "on-tertiary-container": "#646464",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#dcb8ff",
        "secondary-container": "#5c3783",
        "error-container": "#93000a",
        primary: "#ffffff",
        "on-primary": "#2f3131",
        "accent-lavender": "#B48CDE",
        "on-secondary-container": "#d0a7fb",
        secondary: "#dcb8ff",
        "on-secondary-fixed": "#2b0052",
        "primary-container": "#e2e2e2",
        "on-tertiary": "#303030",
        "inverse-primary": "#5d5f5f",
        "outline-variant": "#444748",
        outline: "#8e9192",
        error: "#ffb4ab",
        "surface-tint": "#c6c6c7",
        "text-secondary": "#A1A1AA",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#2a2a2c",
        "tertiary-container": "#e2e2e2",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        surface: "#131315",
        "surface-variant": "#353437",
        "on-secondary-fixed-variant": "#593580",
        "surface-container-highest": "#353437",
        "secondary-fixed": "#efdbff",
        "primary-fixed-dim": "#c6c6c7",
        "on-secondary": "#421c68",
        "on-background": "#e5e1e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-geist-sans)", "sans-serif"],
        "headline-xl": ["var(--font-geist-sans)", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "sans-serif"],
        "headline-sm": ["var(--font-geist-sans)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-geist-sans)", "sans-serif"],
        "body-lg": ["var(--font-geist-sans)", "sans-serif"],
        "body-md": ["var(--font-geist-sans)", "sans-serif"],
        "body-sm": ["var(--font-geist-sans)", "sans-serif"],
        sans: ["var(--font-geist-sans)", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-xl": ["60px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        "soft-md": "0 4px 20px rgba(0,0,0,0.3)",
      },
    },
  },
  plugins: [],
};
export default config;
